### ISSUE TITLE
[Docs] Grab-bag tracker #1

### ISSUE THREAD

**Issue by NiloCK** [polymerdao/monomer#178]
This issue is a personal work tracker to
- plan immediate-term work
- seek feedback
- track progress

Planned work:
- [ ] Adding an extended description of how monomer works
- [ ] Adding instructions for deploying with the OP Stack (not just Monomer + spawn app)
- [x] familiarize self (@NiloCK) with existing docs and contained workflows (eg, monomer integration via `spawn` tool)
- [ ] create a docs section with rationale on known deviations from
  - op-spec (eg: signed deposits tx message)
  - cosmos spec (?)
- return to edit this
