### ISSUE TITLE
Monogen v2

### ISSUE THREAD

**Issue by joshklop** [polymerdao/monomer#227]
Our monogen script is functional but leaves some things to be desired.

```[tasklist]
### Tasks
- [ ] Ensure all generated tests pass
- [ ] Remove unnecessary code and modules, even if the app compiles and runs without them (staking and distribution)
- [ ] Resolve [this](https://github.com/polymerdao/monomer/blob/b31e14534db053c2749ebb6024b1ee33e73c10ee/monogen/monogen_test.go#L59-L60) TODO
```
